### ISSUE TITLE
Add Systemd startup service

### ISSUE THREAD

**Issue by mstrobl2** [dobek/fstrimDaemon#1]
It would be nice to also have a systemd start script as well. I made a simple one that works but has the following limitations (since I'm not very good with systemd):

1) No check that conf file exists and is valid
2) starts the service at normal priority (ignores nice level).

File: /usr/lib/systemd/system/fstrimdemon.service

Contents:

[Unit]
Description=Automated execution of SSD trim command
After=syslog.target

[Service]
ExecStart=/usr/sbin/fstrimDemon.sh

[Install]
WantedBy=multi-user.target

**Comment by dobek** [comment]
I'm not systemd expert either. Can you create a pull request? I suppose that we want to add it also to install/unistall scripts just for keeping it consistent.

**Comment by mstrobl2** [comment]
Sure. Working on a pull request now. I also updated the install/uninstall scripts.

**Comment by dobek** [comment]
Merged and closing.
