### ISSUE TITLE
Add feature

### ISSUE THREAD

**Issue by ghost** [dobek/fstrimDaemon#3]
It is simple to add a multi mount-point (multi TRIM_DIR) trim in the fstrimDemon. Can you add this code?
In the fstrimDemon-master/usr/sbin/fstrimDemon.sh at row 71 (time fstrim -v ${TRIM_DIR}) add the code:

for DIR in ${TRIM_DIR}; do
    time fstrim -v ${DIR}
done

In the config file at line 4 add the feature:

Directories for which fstrim will be run
TRIM_DIR="/ /home /boot"

**Comment by dobek** [comment]
Feature added:
https://github.com/dobek/fstrimDemon/commit/42b5d6406a179a51e024d90d073a50182974d119
