### ISSUE TITLE
Directories for which fstrim will be run

### ISSUE THREAD

**Issue by lehtoj** [dobek/fstrimDaemon#6]
Hello,

It seems like this config option is manual and I have a suggestion. When this config option is left empty, the daemon could use following method to determine which mount points supports TRIM.

```
for fs in $(lsblk -o MOUNTPOINT,DISC-MAX,FSTYPE | grep -E '^/.* [1-9]+.* ' | awk '{print $1}'); do
    fstrim "$fs"
done
```

This trick shamelessly borrowed from http://blog.neutrino.es/2013/howto-properly-activate-trim-for-your-ssd-on-linux-fstrim-lvm-and-dmcrypt/

**Comment by dobek** [comment]
I've tried 

```
for fs in $(lsblk -o MOUNTPOINT,DISC-MAX,FSTYPE | grep -E '^/.* [1-9]+.* ' | awk '{print $1}'); do
    echo "$fs"
done
```

but it didn't work for me.

**Comment by dobek** [comment]
It's because I have raid and luks thus it's more complicated.

**Comment by dobek** [comment]
I've invented something else:
https://github.com/dobek/fstrimDaemon/commit/97ec4ab86733125d49931dfa7d78d40ca7c2f909
